function tictactoe(action,hcbo,hcbf,ht)


maxnr_train = 10000;
fig = 999; % Main panel
if nargin==0, % No callback
    eval(['load ' 'kass'])    
    eval(['save ' 'own' ' state_list Q_table  n_states novel'])

    figure(fig);
    % Save the state of the figure (to be restored later)
    userdata = get(fig, 'UserData');
    userdata.oldFigureUIState = uisuspend(fig);
    userdata.menubar = get(fig,'menubar');
    userdata.resize = get(fig,'resize');
 
    userdata.FontSize = 14;
    units = 'points';
    su = get(0,'Units');
    set(0,'Units',units);
    screensize = get(0,'ScreenSize');
    set(0,'Units',su);

    userdata.nr_train = 0; % set number of training games (% of max number 1000)
    userdata.start = 1; % machine begins % 2 you begin
    
    %panel_pos = [10 0];
    panel_pos = [50 50];
    panel_sz = screensize(3:4)-[100 100];

    buttonpos_x = panel_sz(1)-170;
    button_sz = [160 30];
    slider_sz = [100 20];

    color = [0.7 0.7 0.8];
    instructioncolor = [0 0 1];
    buttoncolor = [0.7 0.7 0.7];

    
    machinestartbutton_pos = [buttonpos_x  panel_sz(2)-40 button_sz(1)/2 button_sz(2)];
    youstartbutton_pos = [buttonpos_x+button_sz(1)/2  panel_sz(2)-40 button_sz(1)/2 button_sz(2)];
    starttext_pos = [buttonpos_x  panel_sz(2)-70 button_sz(1) button_sz(2)];
    playuntrainedbutton_pos = [buttonpos_x  panel_sz(2)-140 button_sz(1) button_sz(2)];
    trainbutton_pos = [buttonpos_x  panel_sz(2)-240 button_sz(1) button_sz(2)];
    traintext_pos = [buttonpos_x  panel_sz(2)-270 button_sz(1) button_sz(2)];
    trainslider_pos = [buttonpos_x  panel_sz(2)-280 button_sz(1) slider_sz(2)];
    resettrainbutton_pos = [buttonpos_x  panel_sz(2)-340 button_sz(1) button_sz(2)];
    playtrainedbutton_pos = [buttonpos_x  panel_sz(2)-440 button_sz(1) button_sz(2)];
    playyourtrainedbutton_pos = [buttonpos_x  panel_sz(2)-540 button_sz(1) button_sz(2)];
    quitbutton_pos = [buttonpos_x  panel_sz(2)-640 button_sz(1) button_sz(2)];
    instructionstext_pos = [20 200  panel_sz(1)-250 50];%75
    imttext_pos =  [20 50 panel_sz(1)-250 button_sz(2)];

	set(fig,'Color',color, ...
	'MenuBar','none', ...
	'Name','TIC TAC TOE', ...
	'NumberTitle','off', ...
	'Units',units, ...
	'Position',[panel_pos(1) panel_pos(2) panel_sz(1) panel_sz(2)], ...
	'Resize','off', ...
	'WindowButtonMotionFcn','tictactoe(''hlptxt'',gcbo,gcbf,'''')');

    % define controls
 
    % machinestart
     h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''machinestart'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',machinestartbutton_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Machine', ...
	'Tag','machinestartbutton');

    % youstart
     h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''youstart'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',youstartbutton_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','You', ...
	'Tag','youstartbutton');

    % starttext
    h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',color, ...
	'ListboxTop',0, ...
	'Position',starttext_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Who begin?', ...
	'Style','text', ...
	'Tag','starttext');
 
    % playuntrained
     h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''playuntrained'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',playuntrainedbutton_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
        'String','Play untrained', ...
	'Tag','playuntrainedbutton');
%	'String','playuntrained', ...   
    % train
     h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''train'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',trainbutton_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Train machine', ...
	'Tag','trainbutton');
%	'String','train', ...
    % traintext
    h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',color, ...
	'ListboxTop',0, ...
	'Position',traintext_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Training (max 10000)', ...
	'Style','text', ...
	'Tag','traintext');
      
    % trainslider
    h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''trainslider'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',trainslider_pos, ...
	'String','training games', ...
	'Style','slider', ...
	'Tag','trainslider', ...
	'Value',userdata.nr_train);

        % resettrain
     h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''resettrain'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',resettrainbutton_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Reset training', ...
	'Tag','resettrainbutton');

    % playtrained
     h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''playtrained'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',playtrainedbutton_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Play trained', ...
	'Tag','playtrainedbutton');

    % playyourtrained
     h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''playyourtrained'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',playyourtrainedbutton_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Play your trained', ...
	'Tag','playyourtrainedbutton');

    % instruction
    
    h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor/0.7*0.9, ...
	'ForegroundColor',instructioncolor, ...
	'ListboxTop',0, ...
	'Position',instructionstext_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','', ...
	'Style','text', ...
	'Tag','instruction');

    % info
    
    h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor/0.7*0.9, ...
	'ForegroundColor',instructioncolor, ...
	'ListboxTop',0, ...
	'Position',instructionstext_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','', ...
	'Style','text', ...
	'Tag','info');

    % quit
    
    h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',buttoncolor, ...
	'Callback','tictactoe(''quit'',gcbo,gcbf)', ...
	'ListboxTop',0, ...
	'Position',quitbutton_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Quit game', ...
	'Tag','quit');

       % starttext
    h1 = uicontrol('Parent',fig, ...
	'Units',units, ...
	'BackgroundColor',color, ...
	'ListboxTop',0, ...
	'Position',imttext_pos, ...
	'FontSize',userdata.FontSize, ...
	'FontWeight','bold', ...
	'String','Institutionen för medicinsk teknik', ...
	'Style','text', ...
	'Tag','imttext');
 
    % game area
    image_pos = [0.3 0.5 0.2 0.4];    
    userdata.h_image = subplot('position',image_pos);axis off;    
    
    % result 
    userdata.result = []; % result image
    userdata.juststarted = 1;
    
    set(fig, 'Userdata', userdata);    
    
    subplot(userdata.h_image);cla
    figure(fig);
    subplot(userdata.h_image);cla
    draw_grid('Machine','You');

else % (nargin > 0) Callback
    
    switch action
	case 'machinestart',	    
	    udata = get(hcbf, 'Userdata');
	    udata.start = 1;
	    set(hcbf, 'Userdata', udata);		    
	case 'youstart',	    
	    udata = get(hcbf, 'Userdata');
	    udata.start = 2;
	    set(hcbf, 'Userdata', udata);		    
	case 'playuntrained',	    
	    udata = get(hcbf, 'Userdata');
	    %tictactoe('instruction',gcbo,gcbf)
	    subplot(udata.h_image);cla
	    figure(fig);
	    subplot(udata.h_image);cla
	    if(udata.start==1)
		play(1,'kass');	
	    else
		play2(1,'kass');	
	    end;
	    set(hcbf, 'Userdata', udata);		    
	case 'train',
	    udata = get(hcbf, 'Userdata');
	    subplot(udata.h_image);cla
	    figure(fig);
	    subplot(udata.h_image);cla
	    nrtraining = max(1,round(maxnr_train*udata.nr_train));
            if(nrtraining==1)
		tmp = ['Learning system ' int2str(nrtraining) ' game' '....'];
	    else
		tmp = ['Learning system ' int2str(nrtraining) ' games' '....'];		
	    end;
	    tictactoe('info',gcbo,gcbf,tmp)
	    pause(2)
	    trainq(nrtraining,'own');
	    subplot(udata.h_image);cla
	    figure(fig);
	    subplot(udata.h_image);cla
	    draw_grid('Machine','You');
	    set(hcbf, 'Userdata', udata);		    	    
	    
	case 'trainslider',
	    udata = get(hcbf, 'Userdata');
	    udata.nr_train = min(1,max(eps,get(hcbo,'Value')));
	    set(hcbf, 'Userdata', udata);	    	    
	case 'resettrain',
	    udata = get(hcbf, 'Userdata');
	    eval(['load ' 'kass'])
	    eval(['save ' 'own' ' state_list Q_table  n_states novel'])
		
	    set(hcbf, 'Userdata', udata);		    	    
	case 'playtrained',
	    udata = get(hcbf, 'Userdata');
	    subplot(udata.h_image);cla
	    figure(fig);
	    subplot(udata.h_image);cla
	    if(udata.start==1)
		play(1,'good');	
	    else
		play2(1,'good');	
	    end;

	    set(hcbf, 'Userdata', udata);		    
	case 'playyourtrained',
	    udata = get(hcbf, 'Userdata');
	    subplot(udata.h_image);cla
	    figure(fig);
	    subplot(udata.h_image);cla
	    if(udata.start==1)
		play(1,'own');	
	    else
		play2(1,'own');	
	    end;
	    set(hcbf, 'Userdata', udata);		    
	    
	case 'quit',
	    figure(fig);clf;
	    udata = get(fig, 'Userdata');
	    uirestore(udata.oldFigureUIState);
	    set(fig, 'Userdata', []);
	    set(fig, 'Menubar', udata.menubar);
	    set(fig, 'Resize', udata.resize);
	    delete(fig);
	    disp('Function terminated');
 	case 'instruction',
	    cp = get(hcbf,'CurrentPoint');  % cursor position
	    h = findobj(hcbf,'Tag','instruction'); % help text object
	    htxt = {''                      % list of help text messages
		'play against untrained machine'
		'show how the system learn by playing against it self'
		'play against trained machine'
		'quit game'};
	    taglist = {'playuntrained'   
		'train'
		'playtrained'
		'quit'};
	    k = onobject(hcbf,cp,taglist);  % Check if cp is on object in list
	    set(h,'String',htxt{k+1});      % Print help text	    
	    pause(2)
 	case 'info',
	    h = findobj(hcbf,'Tag','info'); % help text object
	    set(h,'String',ht);      % Print help text	    
	otherwise,
	    %tmp = ['Press a button'];
	    %tictactoe('info',gcbo,gcbf,tmp)

	    %disp('Unknown method');
    end   
   
	    
	
end;

%---- Local functions ----

function k = onobject(hcbf,cp,taglist)
% Check if pointer is over an object

k = 0;
for n = 1:length(taglist)
    h = findobj(hcbf,'Tag',taglist{n});
    pos = get(h,'Position');
    if ((cp(1)>pos(1)) & (cp(1)<pos(1)+pos(3)) & (cp(2)>pos(2)) & (cp(2)<pos(2)+pos(4)))
	k = n;
	break
    end
end
