bgcolor = [0.8 0.2 0.2];
textcolor = [1 1 1];
buttoncolor = [0.6 0.2 0.2];
nr = 0;
x = [];
d = [];
f = figure;
set(f,'Units','Centimeters',...
      'Position',[5 0.5 35 25],...
      'Name','Classification',...
      'NumberTitle','off',...
      'Color',bgcolor,...
      'Render','Zbuffer');

a = axes;

newdiagnosis
uicontrol(f,'Style','Text',...
	  'Units','Centimeters',...
	  'String','Learn the computer to diagnose diseases',...
	  'HorizontalAlignment','Left',...
	  'FontName','Times',...
	  'FontSize',20,...
	  'Position',[1 22.5 12 1.5],...
	  'ForegroundColor',textcolor,...
	  'BackgroundColor',bgcolor);



reset=uicontrol(f,'Style','PushButton',...
		'Units','Centimeters',...
		'String','Restart',...
		'FontName','Times',...
		'FontSize',17,...
		'Position',[4 3 4 2],...
		'ForegroundColor',textcolor,...
		'BackgroundColor',buttoncolor,...
		'ToolTipString','Press to restart!',...
		'Callback',...
		['nr = 0; x = []; d = []; cla reset,'...
		 'set(instruktion,''String'',''Click four times in the white window!''),'...
		 'set(info,''String'',''Each point corresponds to one measurement of blood pressure and temperature on a patient. Each color corresponds to one disease.''),'...
		 'newdiagnosis']);

hidden=uicontrol(f,'Style','edit',...
		'Units','Centimeters',...
		'String','4',...
		'FontName','Times',...
		'FontSize',14,...
		'Position',[7 11.2 2 1],...
		'ForegroundColor',textcolor,...
		'BackgroundColor',buttoncolor,...
		'ToolTipString','Number of hidden nodes.');

uicontrol(f,'Style','text',...
	  'Units','Centimeters',...
	  'String','Number of hidden nodes.',...
	  'FontName','Times',...
	  'FontSize',14,...
	  'HorizontalAlignment','Left',...
	  'Position',[1 11 6 1],...
	  'ForegroundColor',textcolor,...
	  'BackgroundColor',bgcolor,...
	  'ToolTipString','Number of hidden nodes.')

learnrate=uicontrol(f,'Style','edit',...
		'Units','Centimeters',...
		'String','0.001',...
		'FontName','Times',...
		'FontSize',14,...
		'Position',[7 9.2 2 1],...
		'ForegroundColor',textcolor,...
		'BackgroundColor',buttoncolor,...
		'ToolTipString','Learning rate.');

uicontrol(f,'Style','text',...
	  'Units','Centimeters',...
	  'String','Learning rate',...
	  'FontName','Times',...
	  'FontSize',14,...
	  'HorizontalAlignment','Left',...
	  'Position',[1 9 6 1],...
	  'ForegroundColor',textcolor,...
	  'BackgroundColor',bgcolor,...
	  'ToolTipString','Specifies how fast the network will learn.')

epochs=uicontrol(f,'Style','edit',...
		'Units','Centimeters',...
		'String','400',...
		'FontName','Times',...
		'FontSize',14,...
		'Position',[7 7.2 2 1],...
		'ForegroundColor',textcolor,...
		'BackgroundColor',buttoncolor,...
		'ToolTipString','Number of epochs');

uicontrol(f,'Style','text',...
	  'Units','Centimeters',...
	  'String','Number of epochs',...
	  'FontName','Times',...
	  'FontSize',14,...
	  'HorizontalAlignment','Left',...
	  'Position',[1 7 6 1],...
	  'ForegroundColor',textcolor,...
	  'BackgroundColor',bgcolor,...
	  'ToolTipString','Specifies how many times the training data will be presented for the network')







uicontrol(f,'Style','Text',...
	  'Units','Centimeters',...
	  'String','Department of Biomedical Engineering',...
	  'HorizontalAlignment','Left',...
	  'FontName','Times',...
	  'FontSize',20,...
	  'FontAngle','Italic',...
	  'Position',[1 0.5 15 1.5],...
	  'ForegroundColor',textcolor,...
	  'BackgroundColor',bgcolor);


instruktion = uicontrol(f,'Style','Text',...
			'Units','Centimeters',...
			'String','Click 4 times in the white window!',...
			'FontName','Times',...
			'FontSize',22,...
			'Position',[0 18 14 1.5],...
			'ForegroundColor',[1 1 0],...
			'BackgroundColor',bgcolor);

info = uicontrol(f,'Style','Text',...
		 'Units','Centimeters',...
		 'String','Each point corresponds to one measurement of blood pressure and temperature on a patient. Each color corresponds to one disease.',...
		 'FontName','Times',...
		 'FontSize',18,...
		 'Position',[2 13 10 4],...
		 'ForegroundColor',textcolor,...
		 'BackgroundColor',bgcolor);

