set(a,'Units','Centimeters',...
      'Position',[14 3 20 20])
     
p = newplot;
set(p,'NextPlot','Add',...
      'ButtonDownFcn',...
      ['pos = get(p,''CurrentPoint'');,'...
       'temp = repmat([4+6*rand 0.3+0.7*rand]'',1,200).*randn(2,200);'...
       'nr = nr + 1;'...
       'x = [x  temp + repmat(pos(1,1:2)'',1,200)];'...
       'd = [d nr*ones(1,200)];'...
       'switch nr,'...
       'case 1,'...
       ' plot(temp(1,:)+pos(1,1),temp(2,:)+pos(1,2),''.r''),'...
       'case 2,'...
       ' plot(temp(1,:)+pos(1,1),temp(2,:)+pos(1,2),''.g''),'...
       'case 3,'...
       ' plot(temp(1,:)+pos(1,1),temp(2,:)+pos(1,2),''.b''),'...
       'case 4,'...
       ' plot(temp(1,:)+pos(1,1),temp(2,:)+pos(1,2),''.y''),'...
       'end,'...
       'axis([100 200 34 44]),'...
       'drawnow,'...
       'if nr ==4,'...
       ' set(reset,''Enable'',''off''),'...
       ' set(info,''String'',''The computer learns from the "patient measurements" you have entered by clicking.''),'...
       ' drawnow,'...
       ' backprop,'...
       ' set(reset,''Enable'',''on''),'...
       ' set(instruktion,''String'',''Press the button below to restart!''),'...
       ' set(info,''String'',''The colored areas indicate what diagnose the computer would classify based on the measurements of blood pressure and temperature.''),'...
       'end'])

plot(100,34,'.w')
axis([100 200 34 44])
ylabel('Temperature','Fontsize',15,'FontName','Times');
xlabel('Blood Pressure','Fontsize',15,'FontName','Times');
